### ISSUE TITLE
Time estimation

### ISSUE THREAD

**Issue by rougier** [apdavison/bulbnet-reproduction#2]
Do you have by any chance a rough estimate of the compute time for the different figures ? For the review, I don't think I'll re-run everything and if possible, I will re-run the fastest ones.

**Comment by apdavison** [comment]
Less than 5 minutes: fig 2, 4, 5, 7
5-10 minutes: fig 3, 8, 15, 17
10-60 minutes: fig 9, 11, 12, 14, 16
more than 1 hour: fig 10, 13
